bladeColor = {
    "Blue": "Blue",
    "Green": "Green",
    "Red": "Red",
    "Yellow": "Yellow",
    "Orange": "Orange",
    "Cyan": "Cyan",
    "Purple": "Purple",
    "Pink": "Pink",
    "Silver": "Silver",
    "White": "White",
    "Black": "Black"
}

emitterType = {
    "Inquisitor": "Inquisitor",
    "Avenger": "Avenger",
    "Defender": "Defender",
    "Paladin": "Paladin",
    "Redeemer": "Redeemer",
    "Devastator": "Devastator",
    "Zealot": "Zealot",
    "Sentinel": "Sentinel",
    "Protector": "Protector",
    "Crusader": "Crusader",
    "Templar": "Templar",
    "Seer": "Seer",
    "Silencer": "Silencer",
    "Liberator": "Liberator",
    "Guardian": "Guardian",
    "Exemplar": "Exemplar",
    "Vindicator": "Vindicator",
    "Vigilante": "Vigilante",
    "Vanquisher": "Vanquisher",
    "Conqueror": "Conqueror",
    "Steward": "Steward",
    "Warden": "Warden",
}

switchType = {
    "Inquisitor": "Inquisitor",
    "Avenger": "Avenger",
    "Defender": "Defender",
    "Paladin": "Paladin",
    "Redeemer": "Redeemer",
    "Devastator": "Devastator",
    "Zealot": "Zealot",
    "Sentinel": "Sentinel",
    "Protector": "Protector",
    "Crusader": "Crusader",
    "Templar": "Templar",
    "Seer": "Seer",
    "Silencer": "Silencer",
    "Liberator": "Liberator",
    "Guardian": "Guardian",
    "Exemplar": "Exemplar",
    "Vindicator": "Vindicator",
    "Vigilante": "Vigilante",
    "Vanquisher": "Vanquisher",
    "Conqueror": "Conqueror",
    "Steward": "Steward",
    "Warden": "Warden",
    }

colorScheme = {
    "BlackSilver": "BlackSilver",
    "SilverBronze": "SilverBronze",
    "BlackGold": "BlackGold",
    "WhiteSilver": "WhiteSilver",
    "RedSilver": "RedSilver",
    "YellowBlack": "YellowBlack",
    "PinkWhite": "PinkWhite",
    "Gold": "Gold",
}

handleType = {
    "Inquisitor": "Inquisitor",
    "Avenger": "Avenger",
    "Defender": "Defender",
    "Paladin": "Paladin",
    "Redeemer": "Redeemer",
    "Devastator": "Devastator",
    "Zealot": "Zealot",
    "Sentinel": "Sentinel",
    "Protector": "Protector",
    "Crusader": "Crusader",
    "Templar": "Templar",
    "Seer": "Seer",
    "Silencer": "Silencer",
    "Liberator": "Liberator",
    "Guardian": "Guardian",
    "Exemplar": "Exemplar",
    "Vindicator": "Vindicator",
    "Vigilante": "Vigilante",
    "Vanquisher": "Vanquisher",
    "Conqueror": "Conqueror",
    "Steward": "Steward",
    "Warden": "Warden",
}

all = list(bladeColor.values()) + list(bladeColor.values()) + list(switchType.values()) + list(
    handleType.values()) + list(colorScheme.values()) + list(emitterType.values())
